### ISSUE TITLE
Build error Liquid exception

### ISSUE THREAD

**Issue by desh2608** [OleVik/personal-academic-website#2]
I am getting the following error while trying to build the page:

` Liquid Warning: Liquid syntax error (line 5): Expected id but found open_square in "item in site.[item.label]" in assets/feed.json
Liquid Exception: nil is not a symbol nor a string in assets/feed.json
jekyll 3.5.1 | Error:  nil is not a symbol nor a string`

**Comment by OleVik** [comment]
This is because this skeleton was developed with an earlier version of Jekyll. You can safely remove feed.json and use an alternate method to provide a feed, should you need it. The sitemap-plugin for Jekyll is an excellent alternative, and as I recall it is compatible with GitHub Pages. The [most recent commit](https://github.com/OleVik/personal-academic-website/commit/105e3a514f66c5bdab1cdbd15f79fc58ad2d918a) implements this change.
