### ISSUE TITLE
Question on modifying CSS

### ISSUE THREAD

**Issue by pickettj** [OleVik/personal-academic-website#3]
Ole, I like the look of your personal academic website template a lot, and am trying to modify it for my own purposes. Apologies for what is surely a novice question (I am using Jekyll for the first time), but how can I modify the CSS? E.g. if I want to modify things like background color, margins, etc.? I can get the layout to look the way I want it to when I manually tinker with the main CSS file, but that gets rebuilt and replaced every time I serve the site. And [these instructions seem to get at what I am trying to do](https://tomkadwill.com/2017/12/16/how-to-override-css-styles-in-jekyll.html"), but I can't get them to work in the case of your Jekyll site template.

For instance, I was hoping to do something like the following, but only get an error message when I serve the site:

```
---
---
@import "personal-academic-website";

.sidebar.col-md-3 {
	background: #C8D5EA;
}

```

Any help appreciated!

**Comment by OleVik** [comment]
By main CSS file, are you referring to [assets/css/main.css](https://github.com/OleVik/personal-academic-website/blob/master/assets/css/main.css)? Where are you adding that piece of code? As this is basic CSS, not a preprocessor-setup, `@import "personal-academic-website";` is likely to fail.

Given how [the CSS-files are loaded](https://github.com/OleVik/personal-academic-website/blob/master/_includes/head.html#L11-L13), you'll want to either
A) Create a CSS-file with your own modifications and add it to the bottom of this list, so it loads lasts.
B) Add your customizations at the bottom of main.css, so that directives load last.

You'll also want to make sure that new directives take precedence, in that they have the same- or higher-level of specificity in selectors. `.sidebar.col-md-3 {background: #C8D5EA;}` will be applied if it's loaded after the current content main.css, which [adds a white background](https://github.com/OleVik/personal-academic-website/blob/master/assets/css/main.css#L100).

**Comment by pickettj** [comment]
That worked! Thanks so much for your quick, helpful response, @OleVik !
